apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-stateful-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: 5Gi
  hostPath:
    # path: /home/vagrant/esdata
    path: /run/desktop/mnt/host/c/esdata
    type: DirectoryOrCreate